apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    upstream backend {
        server app-1-svc:8001;
        server app-2-svc:8001;
    }

    server {
        location / {
            proxy_pass http://backend;
        }
    }